### ISSUE TITLE
OPCUA doesn't work after 2024.10 update

### ISSUE THREAD

**Issue by paolomorabito** [minix1234/hacore_opcua#13]
After 2024.10 update I receive these errors:

```
Setup of package 'dosatrice' failed: Requirements for opcua not found: ['opcua==0.98.12'].
Setup of package 'pastorizzatore' failed: Requirements for opcua not found: ['opcua==0.98.12'].
Platform error 'sensor' from integration 'opcua' - Requirements for opcua not found: ['opcua==0.98.12'].
Platform error 'sensor' from integration 'opcua' - Requirements for opcua not found: ['opcua==0.98.12'].
```

In fact https://www.home-assistant.io/integrations/opcua has been deleted
How to fix?

**Comment by Kassem-ajjan** [comment]
i think we need to move to asyncua https://github.com/KVSoong/asyncua 
the only problem i have is if i change i will need to delete all the sensors so the new ones have the right name

**Comment by paolomorabito** [comment]
To fix this problem I found this solution

1. Install opcua on HA. Using Terminal in your HA evirorment: `pip install opcua` or `sudo pip install opcua`
2. Using editor, open file `mainfest.json` in `/custom_components/opcua` folder and replace everything with:

{
    "domain": "opcua",
    "name": "Opcua",
    "documentation": "https://www.home-assistant.io/integrations/opcua",
    "requirements": ["opcua==0.98.13"],
    "codeowners": ["@minix1234"],
    "version": "0.1.0"
  }


Note: `"requirements": ["opcua==0.98.13"],` this version must be the same of the opcua you just installed. To see version of opcua: `pip show opcua`

Restart HA and everything should be ok

**Comment by Kassem-ajjan** [comment]
Thank you !
i didnt have to install at all 
i only changed the file /custom-components/opcua/manifest.json, "requirements": ["opcua==0.98.13"], 
thats it and restarted and updated and everything is working
